version: '3'
services:
  php:
    build: ./php/
    volumes:
      - ./api/:/var/www/html
      - ./php/log/php_log:/var/log/php_log:rw
    links:
      - postgres
      - redis
    restart: always
  front-end:
    build: ./front-end/
    volumes:
      - ./front-end/dist:/var/www/html
    links:
      - nginx
    ports:
      - 10000:80
  postgres:
    build: ./postgres/
    environment:
      - POSTGRES_PASSWORD=fahuHU90HJUsdif676HUHUfafalhdfauzerqrfa
      - POSTGRES_USER=test-postgres
      - POSTGRES_DB=test
    ports:
      - 10001:5432
    restart: always
  nginx:
    build: ./nginx/
    volumes:
      - ./nginx/log:/var/log/nginx:rw
      - ./ocm-web:/var/www/html
    links:
      - php:php
    ports:
      - 10002:80
    restart: always
  redis:
    build: ./redis/
    ports:
      - 10003:6379
    restart: always
